name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ./kube-news/src
        file: ./kube-news/src/Dockerfile
        push: true
        tags: igorlage/kube-news:v${{ github.run_number }},igorlage/kube-news:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Autenticar na AWS
      run: echo "Autenticar na AWS"
    - name: Configurar o kubeconfig
      run: echo "Configurar o kubeconfig"
    - name: Aplicar o deploy
      run: echo "Aplicar o deploy"
    
    
    
